Discovery.WebUI/Controllers/ChildController.cs
using Discovery.Core.Models;
using Discovery.DataAccess.SQL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Discovery.WebUI.Controllers
{
    [Authorize(Roles = "Admin,Teacher")]
    public class ChildController : Controller
    {

        DataContext context = new DataContext();

        // GET: Child
        public ActionResult Index(string sortOrder)
        {

            ViewBag.name = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.lastName = sortOrder == "LastN" ? "LastN_desc" : "LastN";
            ViewBag.age = sortOrder == "Age" ? "Age_desc" : "Age";
            ViewBag.grade = sortOrder == "Grade" ? "Grade_desc" : "Grade";
            ViewBag.disability_type = sortOrder == "Disability_Type" ? "Disability_Type_desc" : "Disability_Type";
            ViewBag.classroom = sortOrder == "Classroom" ? "Classroom_desc" : "Classroom";

            List<Child> children = context.Children.ToList();

            switch (sortOrder)
            {
                case "name_desc":
                    children = children.OrderByDescending(c => c.FirstName).ToList();
                    break;
                case "LastN":
                    children = children.OrderBy(c => c.LastName).ToList();
                    break;
                case "LastN_desc":
                    children = children.OrderByDescending(c => c.LastName).ToList();
                    break;
                case "Age":
                    children = children.OrderBy(c => c.Age).ToList();
                    break;
                case "Age_desc":
                    children = children.OrderByDescending(c => c.Age).ToList();
                    break;
                case "Grade":
                    children = children.OrderBy(c => c.Grade).ToList();
                    break;
                case "Grade_desc":
                    children = children.OrderByDescending(c => c.Grade).ToList();
                    break;
                case "Disability_Type":
                    children = children.OrderBy(c => c.Disability_Type).ToList();
                    break;
                case "Disability_Type_desc":
                    children = children.OrderByDescending(c => c.Disability_Type).ToList();
                    break;
                case "Classroom":
                    children = children.OrderBy(c => c.ClassRoom).ToList();
                    break;
                case "Classroom_desc":
                    children = children.OrderByDescending(c => c.ClassRoom).ToList();
                    break;
                default:
                    children = children.OrderBy(c => c.FirstName).ToList();
                    break;
            }

            return View(children);
        }


        [HttpPost]
        public JsonResult doSearch(string Search, string Option)
        {

            List<Child> children;
            switch (Option)
            {
                case "option2":
                    children = context.Children.Where(c => c.LastName.StartsWith(Search)).ToList();
                    break;
                case "option3":
                    children = context.Children.Where(c => c.Disability_Type.StartsWith(Search)).ToList();
                    break;
                default:
                    children = context.Children.Where(c => c.FirstName.StartsWith(Search)).ToList();
                    break;
            }

            return Json(children, JsonRequestBehavior.AllowGet);
        }



        public ActionResult Create()
        {
            Child c = new Child();

            return View(c);
        }

        [HttpPost]
        public ActionResult Create(Child c)
        {
            if (!ModelState.IsValid)
            {
                return View(c);
            }
            else
            {
                if(c.ClassRoom != null)
                {
                    c.TeacherId = context.Teachers.FirstOrDefault(t => t.ClassRoom == c.ClassRoom).Id;
                }
                

                Parent parent = new Parent();
                parent.ChildId = c.Id;

                context.Parents.Add(parent);
                context.Children.Add(c);
                context.SaveChanges();

                return RedirectToAction("Index");
            }
        }

        public ActionResult Edit(string Id)
        {
            Child c = context.Children.Find(Id);

            if(c == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(c);
            }
        }

        [HttpPost]
        public ActionResult Edit(Child c,string Id)
        {
            Child cToEdit = context.Children.Find(Id);

            if(cToEdit == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    return View(c);
                }
                else
                {

                    cToEdit.FirstName = c.FirstName;
                    cToEdit.LastName = c.LastName;
                    cToEdit.Age = c.Age;
                    cToEdit.TeacherId = c.TeacherId;
                    cToEdit.ClassRoom = c.ClassRoom;
                    cToEdit.Grade = c.Grade;
                    cToEdit.Degree = c.Degree;
                    cToEdit.Disability_Type = c.Disability_Type;

                    if (cToEdit.ClassRoom != null)
                    {
                        Teacher teacher = context.Teachers.FirstOrDefault(t => t.ClassRoom == c.ClassRoom);
                        cToEdit.TeacherId = teacher == null ? null : teacher.Id;
                    }

                    context.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
        }

        public ActionResult Details(string Id)
        {
            Child c = context.Children.Find(Id);

            if(c == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(c);
            }
        }


        public ActionResult Delete(string Id)
        {
            Child c = context.Children.Find(Id);

            if(c == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(c);
            }
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult ConfirmDelete(string Id)
        {
            Child cToDelete = context.Children.Find(Id);

            if(cToDelete == null)
            {
                return HttpNotFound();
            }
            else
            {
                Parent pToDelete = context.Parents.FirstOrDefault(p => p.ChildId == cToDelete.Id);
                context.Children.Remove(cToDelete);
                if(pToDelete != null)
                {
                    context.Parents.Remove(pToDelete);
                }

                context.SaveChanges();

                return RedirectToAction("Index");
            }
        }

    }
}

Discovery.WebUI/Controllers/EmployerController.cs
using Discovery.Core.Models;
using Discovery.DataAccess.SQL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Discovery.WebUI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EmployerController : Controller
    {
        DataContext context = new DataContext();

        // GET: Employer
        public ActionResult Index(string sortOrder)
        {

            ViewBag.name = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.lastName = sortOrder == "LastN" ? "LastN_desc" : "LastN";
            ViewBag.age = sortOrder == "Age" ? "Age_desc" : "Age";
            ViewBag.street = sortOrder == "Street" ? "Street_desc" : "Street";
            ViewBag.job = sortOrder == "Job" ? "Job_desc" : "Job";
            ViewBag.salary = sortOrder == "Salary" ? "Salary_desc" : "Salary";

            List<Employee> employees = context.Employees.ToList();

            switch (sortOrder)
            {
                case "name_desc":
                    employees = employees.OrderByDescending(e => e.FirstName).ToList();
                    break;
                case "LastN":
                    employees = employees.OrderBy(e => e.LastName).ToList();
                    break;
                case "LastN_desc":
                    employees = employees.OrderByDescending(e => e.LastName).ToList();
                    break;
                case "Age":
                    employees = employees.OrderBy(e => e.Age).ToList();
                    break;
                case "Age_desc":
                    employees = employees.OrderByDescending(e => e.Age).ToList();
                    break;
                case "Street":
                    employees = employees.OrderBy(e => e.Street).ToList();
                    break;
                case "Street_desc":
                    employees = employees.OrderByDescending(e => e.Street).ToList();
                    break;
                case "Job":
                    employees = employees.OrderBy(e => e.Job).ToList();
                    break;
                case "Job_desc":
                    employees = employees.OrderByDescending(e => e.Job).ToList();
                    break;
                case "Salary":
                    employees = employees.OrderBy(e => e.Salary).ToList();
                    break;
                case "Salary_desc":
                    employees = employees.OrderByDescending(e => e.Salary).ToList();
                    break;
                default:
                    employees = employees.OrderBy(e => e.FirstName).ToList();
                    break;
            }

            return View(employees);
        }

        [HttpPost]
        public JsonResult doSearch(string Search, string Option)
        {
            List<Employee> employees;
            switch (Option)
            {
                case "option2":
                    employees = context.Employees.Where(e => e.LastName.StartsWith(Search)).ToList();
                    break;
                case "option3":
                    employees = context.Employees.Where(e => e.Job.StartsWith(Search)).ToList();
                    break;
                case "option4":
                    employees = context.Employees.Where(e => e.Salary.ToString().StartsWith(Search)).ToList();
                    break;
                default:
                    employees = context.Employees.Where(e => e.FirstName.StartsWith(Search)).ToList();
                    break;
            }


            return Json(employees, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Employee e)
        {
            context.Employees.Add(e);
            context.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult Edit(string Id)
        {
            Employee e = context.Employees.Find(Id);

            if (e == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(e);
            }
        }

        [HttpPost]
        public ActionResult Edit(Employee e, string Id)
        {
            Employee eToEdit = context.Employees.Find(Id);

            if (eToEdit == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    return View(e);
                }
                else
                {
                    eToEdit.FirstName = e.FirstName;
                    eToEdit.LastName = e.LastName;
                    eToEdit.Age = e.Age;
                    eToEdit.Street = e.Street;
                    eToEdit.Job = e.Job;
                    eToEdit.Salary = e.Salary;


                    context.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
        }

        public ActionResult Details(string Id)
        {
            Employee e = context.Employees.Find(Id);

            if (e == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(e);
            }
        }


        public ActionResult Delete(string Id)
        {
            Employee e = context.Employees.Find(Id);

            if (e == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(e);
            }

        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult ConfirmDelete(string Id)
        {
            Employee eToDelete = context.Employees.Find(Id);

            if (eToDelete == null)
            {
                return HttpNotFound();
            }
            else
            {
                context.Employees.Remove(eToDelete);
                context.SaveChanges();

                return RedirectToAction("Index");
            }
        }

    }
}

Discovery.WebUI/Controllers/ParentController.cs
using Discovery.Core.Models;
using Discovery.Core.VIewModels;
using Discovery.DataAccess.SQL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Discovery.WebUI.Controllers
{
    [Authorize]
    public class ParentController : Controller
    {
        // GET: Parent
        DataContext context = new DataContext();

        public PartialViewResult ChildReport(string Id)
        {

            Parent parent = context.Parents.FirstOrDefault(p => p.ChildId == Id);

            
            Child child = context.Children.FirstOrDefault(c => c.Id == Id);
            NurseryUser user = context.Users.FirstOrDefault(u => u.Id == parent.UserId);
            

            ParentUserChildViewModel model = new ParentUserChildViewModel();

            model.user = user;
            model.child = child;
            model.parent = parent;

            return PartialView("_ChildReport", model);
        }


        [HttpPost]
        public ActionResult Edit(Parent parent)
        {

            Parent pToEdit = context.Parents.Find(parent.Id);

            pToEdit.Child_Weekly_Report = parent.Child_Weekly_Report;

            context.SaveChanges();

            return RedirectToAction("Index", "Child");
        }

    }
}

Discovery.WebUI/Controllers/UserController.cs
using Discovery.Core.Models;
using Discovery.Core.VIewModels;
using Discovery.DataAccess.SQL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Discovery.WebUI.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        DataContext context = new DataContext();

        // GET: User
        public ActionResult Index()
        {
            NurseryUser user = context.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
            return View(user);
        }

        [HttpPost]
        public JsonResult getChild(string Password)
        {
            Child child = context.Children.FirstOrDefault(c => c.Password == Password);

            if(child == null)
            {
                return Json("Not Found", JsonRequestBehavior.AllowGet);
            }
            else
            {
                Teacher teacher = context.Teachers.FirstOrDefault(t => t.Id == child.TeacherId);


                if (teacher == null)
                {
                    teacher = new Teacher()
                    {
                        FirstName = "Not Found",
                        LastName = "Not Found",
                        Email = "Not Found",
                        PhoneNumber = "Not Found",
                        ClassRoom = "Not Found",
                    };
                }



                Parent parent = context.Parents.FirstOrDefault(p => p.ChildId == child.Id);
                if(parent.UserId == null)
                {
                    parent.UserId = context.Users.FirstOrDefault(u => u.Email == User.Identity.Name).Id;
                }
                
                context.SaveChanges();

                TeacherChildViewModel viewModel = new TeacherChildViewModel()
                {
                    CFirstName = child.FirstName,
                    CLastName = child.LastName,
                    CAge = child.Age,
                    CDegree = child.Degree,
                    CClassRoom = child.ClassRoom,
                    CDisability_Type = child.Disability_Type,
                    CGrade = child.Grade,
                    TFirstName = teacher.FirstName,
                    TLastName = teacher.LastName,
                    TEmail = teacher.Email,
                    TPhoneNumber = teacher.PhoneNumber,
                };

                return Json(viewModel, JsonRequestBehavior.AllowGet);
            }

        }

    }
}

Discovery.WebUI/Views/Shared/_ChildReport.cshtml
@model Discovery.Core.VIewModels.ParentUserChildViewModel

<h4>Parent</h4>
<hr />

<div class="row">
    <div class="col-md-6">
        <div class="col-md-7">
            <h3 class="text-center">Parent Info</h3>
        </div>
        <dl class="col-md-12 dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.user.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.user.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.user.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.user.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.user.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.user.Email)
            </dd>
        </dl>
    </div>
    <div class="col-md-6">

        <div class="col-md-7">
            <h3 class="text-center">Child Info</h3>
        </div>

        <dl class="col-md-12 dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.child.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.child.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.child.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.child.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.child.Age)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.child.Age)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.child.Grade)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.child.Grade)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.child.Degree)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.child.Degree)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.child.Disability_Type)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.child.Disability_Type)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.child.ClassRoom)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.child.ClassRoom)
            </dd>

        </dl>
    </div>
</div>

@using (Html.BeginForm("Edit", "Parent", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.parent.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.parent.Child_Weekly_Report, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.parent.Child_Weekly_Report, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.parent.Child_Weekly_Report, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Child")
</div>

Discovery.WebUI/Views/Shared/_ChildReportError.cshtml
@model Discovery.Core.Models.Child

@{
    ViewBag.Title = "Error";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">(@Model.FirstName @Model.LastName) Isnt Linked with Parent account</h2>

<div>
    @Html.ActionLink("Back to List", "Index", "Child")
</div>

Discovery.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Discovery Nursery", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (Request.IsAuthenticated)
                {
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("Admin") || User.IsInRole("Teacher"))
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Children", "Index", "Child", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Teachers", "Index", "Teacher", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Employees", "Index", "Employer", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("AdminControl", "Index", "Admin", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    }
                    <li class="nav-item">
                        @Html.ActionLink("Parent", "Index", "User", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>
                }
                @Html.Partial("_LoginPartial")

                @{
                    Html.RenderAction("getUser", "Home");
                }


            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Discovery.WebUI/Views/Shared/_View.cshtml
@using Microsoft.AspNet.Identity
<!doctype html>
<html lang="en">
<head>

    <link href="https://fonts.googleapis.com/css?family=Courgette|Dancing+Script|Gloria+Hallelujah|Gochi+Hand|Indie+Flower|Pacifico&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=PT+Serif&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fredericka+the+Great&display=swap" rel="stylesheet">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="~/Content/Mine.css" type="text/css" />

    <title>Discovery nursery</title>
</head>


<body>
    <nav style="position: fixed; z-index: 999; background-color: black;" class="w-100 navbar navbar-expand-lg navbar-dark">

        <div class="container">

            @Html.ActionLink("Discovery Nursery", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <!-- Collapse button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Collapsible content -->
            <div class="collapse navbar-collapse" id="basicExampleNav">

                @if (Request.IsAuthenticated)
                {
                    <!-- Links -->
                <ul class="navbar-nav mr-auto">

                    @if (User.IsInRole("Admin") || User.IsInRole("Teacher"))
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Children", "Index", "Child", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    }

                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Teachers", "Index", "Teacher", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Employees", "Index", "Employer", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("AdminControl", "Index", "Admin", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    }
                    <li class="nav-item">
                        @Html.ActionLink("Parent", "Index", "User", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>
                }
                <!-- Links -->

                @{
                    Html.RenderAction("getUser", "Home");
                }


                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()

                        <ul class="nav navbar-nav navbar-right">
                            @{/*
                                  <li style="text-align:end;" class="col-md-8 nav-item">
                                  @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage", @class = "nav-link" })
                              </li>
                              */}
                            <li><a class="nav-link" href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                        </ul>
                    }
                }
                else
                {
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink", @class = "nav-link" })</li>
                        <li class="nav-item">@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "nav-link" })</li>
                    </ul>
                }


                <!-- Collapsible content -->

            </div>
            <!-- Navbar brand -->
            </div>
    </nav>
    <!--/.Navbar-->
    @RenderBody()

    @RenderSection("scripts", required: false)
</body>
</html>

Discovery.WebUI/Views/Shared/_getUser.cshtml
@model Discovery.Core.Models.NurseryUser

@if (Request.IsAuthenticated)
{

    <ul class="nav navbar-nav navbar-right">
        <li class="w-100">
            @Html.ActionLink("Hello " + Model.FirstName + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage", @class = "nav-link" })
        </li>
    </ul>

}